CREATE TABLE COVID(
        REGEI_DATE VARCHAR2(200),
        COVID_NEW_CI  VARCHAR2(200),
        COVID_CONF_CI VARCHAR2(200),
        COVID_CARE_CI VARCHAR2(200),
        COVID_NEWL_CI VARCHAR2(200),
        COVID_LEAVE_CI VARCHAR2(200),
        COVID_DIED_CI VARCHAR2(200),
        COVID_NEW_KO VARCHAR2(200),
        COVID_CONF_KO VARCHAR2(200),
        COVID_CARE_KO VARCHAR2(200),
        COVID_LEAVE_KO VARCHAR2(200),
        COVID_DIED_KO VARCHAR2(200),
        COVID_DATE DATE DEFAULT SYSDATE
        
);
SELECT * FROM COVID;
DROP TABLE COVID;

COMMENT ON COLUMN COVID.COVID_NEW_CI IS '서울 신규확진자';
COMMENT ON COLUMN COVID.COVID_CONF_CI IS '서울 확진자';
COMMENT ON COLUMN COVID.COVID_CARE_CI IS '서울 치료중';
COMMENT ON COLUMN COVID.COVID_NEWL_CI IS '서울 신규퇴원자';
COMMENT ON COLUMN COVID.COVID_LEAVE_CI IS '서울 퇴원자';
COMMENT ON COLUMN COVID.COVID_DIED_CI IS '서울 사망자';
COMMENT ON COLUMN COVID.COVID_NEW_KO IS '한국 신규확진자';
COMMENT ON COLUMN COVID.COVID_CONF_KO IS '한국 확진자';
COMMENT ON COLUMN COVID.COVID_CARE_KO IS '한국 치료중';
COMMENT ON COLUMN COVID.COVID_LEAVE_KO IS '한국 퇴원자';
COMMENT ON COLUMN COVID.COVID_DIED_KO IS '한국 사망자';
COMMENT ON COLUMN COVID.COVID_DATE IS '날짜';

insert into covid values (null,null,null,null,null,null,null,null,null,null, null,sysdate);
CREATE TABLE COVID_SE
AS
SELECT COVID_NEW_CI 신규확진자, COVID_CONF_CI 확진자, COVID_CARE_CI 치료중, COVID_NEWL_CI 신규퇴원, COVID_LEAVE_CI 퇴원, 
            COVID_DIED_CI 사망, COVID_DATE 날짜
FROM COVID;

SELECT * FROM COVID_SE;
drop table covid_se;



CREATE TABLE COVID_KO
AS
SELECT COVID_NEW_KO 신규확진자, COVID_CONF_KO 확진자, COVID_CARE_KO 치료중, COVID_LEAVE_KO 퇴원, 
            COVID_DIED_KO 사망, COVID_DATE 날짜
FROM COVID;

select * from covid_ko;
drop table covid_ko;

SELECT COVID_DATE
FROM COVID;